[package]
name = "code-env"
version = "0.1.0-SNAPSHOT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snailquote = "0.3"

[lib]
proc-macro = true
